### ISSUE TITLE
`bundle.wasm` has the same size when bundled with `--release` flag

### ISSUE THREAD

**Issue by phaleth** [arctic-hen7/perseus#52]
**Describe the bug**
Tried to run `perseus serve` and then `perseus serve --release` and observed that the `bundle.wasm`, as loaded into the web browser, has the same size in both cases. Other than that running the command with the `--release` flag takes significantly longer.

**To Reproduce**
The following example results in `bundle.wasm` size of 329.28 KB.

Cargo.toml
```toml
[package]
name = "perseus-tiny"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
perseus = "0.3.0-beta.6"
sycamore = "0.6"
wee_alloc = "0.4"

[profile.release]
# Do not perform backtrace for panic on release builds.
panic = 'abort'
# Perform optimizations on all codegen units.
codegen-units = 1
# Optimize for size.
opt-level = 's' # 's' or 'z' to optimize "aggressively" for size
# Enable link time optimization. Does not work with Netlify.
lto = true
```

index.html
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Perseus Example – Tiny</title>
    <link data-trunk rel="rust" data-wasm-opt="s" />
</head>

<body>
    <div id="root"></div>
</body>

</html>
```

src/lib.rs
```rust
#[global_allocator]
static ALLOC: wee_alloc::WeeAlloc = wee_alloc::WeeAlloc::INIT;

use perseus::{define_app, ErrorPages, Template};
use std::rc::Rc;
use sycamore::template;
define_app! {
    templates: [
        Template::<G>::new("index").template(Rc::new(|_| {
            template! {
                p { "Hello World!!" }
            }
        }))
    ],
    error_pages: ErrorPages::new(Rc::new(|url, status, err, _| {
        template! {
            p { (format!("An error with HTTP code {} occurred at '{}': '{}'.", status, url, err)) }
        }
    }))
}
```

**Expected behavior**
After running `perseus serve --release` the `bundle.wasm` should be significantly smaller.

**Screenshots**
![image](https://user-images.githubusercontent.com/29838606/136257250-fbe12279-d029-43d7-8fe7-62e3b157577e.png)

**Environment (please complete the following information):**
 - Perseus Version: 0.3.0-beta.6
 - Sycamore Version: 0.6.1
 - OS: debian 10
 - Browser: Firefox
 - Browser Version: 78.14.0esr (64-bit)

**Additional context**
Not really sure if the above is the correct way to bundle for production.
