### ISSUE TITLE
Failed to install `perseus-cli 0.3.0-beta.XX` with `clap 3.0.0-rc.X`

### ISSUE THREAD

**Issue by rieval** [arctic-hen7/perseus#85]
I tried to run the following command: 

`cargo install perseus-cli --version 0.3.0-beta.18`

It threw some similar errors: https://github.com/arctic-hen7/perseus/issues/65#issuecomment-945954443.

Then I noticed that `clap` had released the version `3.0.0-rc.X`, so I tried to editing `Cargo.toml` in the `perseus-cli-0.3.0-beta.18` folder.

```toml
[dependencies.clap]
version = "=3.0.0-beta.5" # <= pin the version
features = ["color"]
```

Finally I run the install command again and it runs successfully.
